site_name: Step-by-Step
site_url: https://fiware-tutorials.readthedocs.org
repo_url: https://github.com/fiware/tutorials.Step-by-Step
site_description: Fiware Tutorial Documentation
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
google_analytics: ["UA-83719923-1", "fiware-tutorials.readthedocs.io"]
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_neutral.css"]
pages:
  - Home: "index.md"
  - "Core Context Managment: NGSI-v2":
      - "Getting Started with NGSI-v2": "getting-started.md"
      - "Entity Relationships": "entity-relationships.md"
      - "CRUD Operations": "crud-operations.md"
      - "Context Providers": "context-providers.md"
      - "Accessing Context": "accessing-context.md"
      - "Subscriptions": "subscriptions.md"
  - "IoT Agents & Robots":
      - "IoT Sensors": "iot-sensors.md"
      - "IoT Agent (Ultralight)": "iot-agent.md"
      - "IoT Agent (JSON)": "iot-agent-json.md"
      - "IoT over MQTT": "iot-over-mqtt.md"
      - "Fast RTPS-Micro RTPS": "fast-rtps-micro-rtps.md"
  - "Core Context Managment: History Management":
      - "Persisting Context (Apache Flume)": "historic-context-flume.md"
      - "Persisting Context (Apache NIFI)": "historic-context-nifi.md"
      - "Short Term History": "short-term-history.md"
      - "Time-Series Data": "time-series-data.md"
  - "Identity Management":
      - "Administrating Users": "identity-management.md"
      - "Managing Roles and Permissions": "roles-permissions.md"
      - "Securing Application Access": "securing-access.md"
      - "Securing Microservices": "pep-proxy.md"
      - "Ruleset-based Permissons": "xacml-access-rules.md"
      - "Administrating XACML Rules": "administrating-xacml.md"
  - "Processing, Analysis and Visualization":
      - "Application Mashups": "application-mashups.md"
      - "Media Streams": "media-streams.md"
      - "Big Data Analysis": "big-data-analysis.md"
      - "Cloud Edge Computing": "edge-computing.md"
  - "NGSI-LD for NGSI-v2 Developers":
      - "Linked Data": "linked-data.md"
      - "Relationships & Data Models": "relationships-linked-data.md"
      - "Traversing Linked Data": "working-with-linked-data.md"
      - "Subscriptions and Registrations": "ld-subscriptions-registrations.md"
  - "Appendix":
      - "Curl Commands": "cmds/administrating-xacml.md"
